sudo: required

notifications:
email: james.hn.sears@gmail.com

addons:
  sonarcloud:
    organization: "jameshnsears-github"
    token:
      secure: "Ga2v1KU0kr5BbVq+beZdNsssk8mfAIEoDjkpMTpDCY5vrg6OAhxrsal6EZPmN/D0KTLv7E+3uQvEaT/DwXx0MSPAcBAHjRyCd4l57k4qiXP/vEpClJ5NUY+risUl7NsthsmISmlA0HEU4v3FSBUENUPrtCT/lJi/01SLjxEQ2tXGLZpVET/Ggw/2C6zTFSwiegnST5jPj12lCeew50N8nnRUdH/9Pmm6elTbmQAvzadwDM0wkyOVD93kOKPUIvJ06pNbmfpIEJO4bvRarw6tTjeCiqX+228fCpwMswDxrqFps//sksMGaNmiBjiiyR7n9yVXHjulzgz+b0YtxbFlMjtLf+fv2fSXf25HA96hQNWa8OHbH2gWnKC6PY2gU351Fy254pBYe4ZzeNq/AwuDFWSQL4HbQQ7Slm3nadhbjo11rw1Igpdm2nHI8C4TFTDcNAM0jb5qX/QZtPeKqRiJJFB4kckIkQaOMI3KnPGArAeBgrQ4TTEm23fS4zkIyoNsYslPD8aupbn8Wr8ThhDXaX0qFBoz88joDXnrHEN3bCp+xEKxs47xNDnpZzsZVHloLQA+zckCIm5YLGScs3XiRfadVDHDoshBjXQXONUJS86Dpz7/WYPEdy7R9RBTBckme1ETeSsUSxKnQ7ZwCol0meiguDtiVhGE4UKrh3E050E="

services:
  - docker

cache:
  directories:
  - $HOME/.sonar/cache

language: python

python:
  - "3.6"

before_script:
  - sudo service postgresql stop
  - while sudo lsof -Pi :5432 -sTCP:LISTEN -t; do sleep 1; done

  - docker-compose pull xqa-db xqa-message-broker

  - pip install --upgrade pip
  - pip install -r requirements.txt
  - flake8 src test

script:
  - export PYTHONPATH=src:$PYTHONPATH
  - pytest -s --cov-report term-missing --cov=. test

after_success:
  - COVERALLS_REPO_TOKEN=E5ojynusVZalBYvI6sMT2HDuN1T2VVtLJ coveralls
  - sonar-scanner
